# This file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Doctrina Católica
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  El Catecismo enlazado con sus fuentes
lang: es
baseurl: /doctrina-catolica # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: materialknight

# Build settings
theme: minima
plugins:
  - jekyll-feed

feed:
  collections:
    - opusculos
    - documentos-eclesiasticos

header_pages:
  - about.markdown
collections_dir: colecciones

collections:
  biblia-straubinger:
    output: true
    permalink: /:collection/:name
  catecismo:
    output: true
    permalink: /:collection/:name
  catecismo-romano:
    output: true
    permalink: /:collection/:name
  compendio-catecismo:
    output: true
  contra-los-herejes:
    output: true
  documentos-eclesiasticos:
    output: true
    permalink: ":path"
  opusculos:
    output: true
    permalink: ":path"

defaults:
  -
    scope:
      path: "_biblia-straubinger"
    values:
      layout: "biblia"
  -
    scope:
      path: "_catecismo"
    values:
      layout: "magnum-opus"
  -
    scope:
      path: "_catecismo-romano"
    values:
      layout: "magnum-opus"
  -
    scope:
      path: "_compendio-catecismo"
    values:
      layout: "magnum-opus"
  -
    scope:
      path: "_contra-los-herejes"
    values:
      layout: "magnum-opus"
  -
    scope:
      path: "_documentos-eclesiasticos"
    values:
      layout: "documento-eclesiastico"
  -
    scope:
      path: "_opusculos"
    values:
      layout: "opusculo"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
